#!/usr/bin/env python
class SettingsManager:
    def __init__(self, name: str, settings_directory: str = None) -> None: ...
    def read(self) -> dict: ...
    def commit(self) -> None: ...
    def getSetting(self, key: str, default: any) -> any: ...
    def setSetting(self, key: str, value: any) -> None: ...
